name: Build Pixel 4a 5G Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential curl flex git \
            gcc-arm-linux-gnueabi \
            libncurses5-dev libssl-dev lz4 \
            python3 python-is-python3 unzip zip

      - name: Create Google kernel layout
        run: |
          mkdir -p kernel/private

      - name: Clone redbull kernel source
        run: |
          git clone --depth=1 \
            -b android-msm-redbull-4.19-android11-qpr3 \
            https://android.googlesource.com/kernel/msm \
            kernel/private/msm-google

      - name: Clone Google kernel build scripts
        run: |
          git clone --depth=1 \
            -b master-kernel-build-2021 \
            https://android.googlesource.com/kernel/build \
            kernel/build

      - name: Add KernelSU-Next legacy
        working-directory: kernel/private/msm-google
        run: |
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy
          
      - name: Apply KernelSU classic hooks with Coccinelle
        working-directory: kernel/private/msm-google
        run: |
          sudo apt-get update
          sudo apt-get install -y coccinelle

          git clone https://github.com/devnoname120/kernelsu-coccinelle ksu-cocci
          cd ksu-cocci
          git checkout 9e30076418813fc7eaab6481da2e745dfde56249
          cd ..

          chmod +x ksu-cocci/classic-hooks/apply.sh
          bash ksu-cocci/classic-hooks/apply.sh .
          
      - name: Enable KernelSU config
        working-directory: kernel/private/msm-google
        run: |
          echo "CONFIG_KSU=y" >> arch/arm64/configs/redbull_defconfig
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/arm64/configs/redbull_defconfig
          echo "# CONFIG_KSU_KPROBE_HOOKS is not set" >> arch/arm64/configs/redbull_defconfig

      - name: Build kernel Image only
        working-directory: kernel
        run: |
          chmod +x build/build.sh
          BUILD_CONFIG=private/msm-google/build.config.redbull.no-cfi build/build.sh

      - name: Show outputs
        run: |
          find kernel -type f \( -name "Image" -o -name "Image.gz" -o -name "Image.lz4" -o -name "Image.lz4-dtb" \) -print

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Pixel4a5G-bramble-kernel
          path: |
            kernel/out/**/Image
            kernel/out/**/Image.gz
            kernel/out/**/Image.lz4
            kernel/out/**/Image.lz4-dtb
